<a href="https://colab.research.google.com/github/AkankshaB123/python/blob/main/StudentsandExamination_CrossJoin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [2]:
students = [
    {"student_id": 1, "student_name": "Alice"},
    {"student_id": 2, "student_name": "Bob"},
    {"student_id": 13, "student_name": "John"},
    {"student_id": 6, "student_name": "Alex"},
]

subjects = [
    {"subject_name": "Math"},
    {"subject_name": "Physics"},
    {"subject_name": "Programming"},
]

examinations = [
    {"student_id": 1, "subject_name": "Math"},
    {"student_id": 1, "subject_name": "Physics"},
    {"student_id": 1, "subject_name": "Programming"},
    {"student_id": 2, "subject_name": "Programming"},
    {"student_id": 1, "subject_name": "Physics"},
    {"student_id": 1, "subject_name": "Math"},
    {"student_id": 13, "subject_name": "Math"},
    {"student_id": 13, "subject_name": "Programming"},
    {"student_id": 13, "subject_name": "Physics"},
    {"student_id": 2, "subject_name": "Math"},
    {"student_id": 1, "subject_name": "Math"},
]

In [3]:
import pandas as pd

students = pd.DataFrame({
    "student_id": [1, 2, 13, 6],
    "student_name": ["Alice", "Bob", "John", "Alex"]
})

subjects = pd.DataFrame({
    "subject_name": ["Math", "Physics", "Programming"]
})

examinations = pd.DataFrame({
    "student_id": [1, 1, 1, 2, 1, 1, 13, 13, 13, 2, 1],
    "subject_name": [
        "Math", "Physics", "Programming", "Programming",
        "Physics", "Math", "Math", "Programming",
        "Physics", "Math", "Math"
    ]
})

In [6]:
examinations['attended_exams'] = 1
df = pd.merge(students, subjects, how='cross')
df_final = pd.merge(df, examinations, on=['student_id', 'subject_name'], how='left')
df_final

    student_id student_name subject_name  attended_exams
0            1        Alice         Math             1.0
1            1        Alice         Math             1.0
2            1        Alice         Math             1.0
3            1        Alice      Physics             1.0
4            1        Alice      Physics             1.0
5            1        Alice  Programming             1.0
6            2          Bob         Math             1.0
7            2          Bob      Physics             NaN
8            2          Bob  Programming             1.0
9           13         John         Math             1.0
10          13         John      Physics             1.0
11          13         John  Programming             1.0
12           6         Alex         Math             NaN
13           6         Alex      Physics             NaN
14           6         Alex  Programming             NaN

In [7]:
df_final.groupby(['student_id','student_name','subject_name'])['attended_exams'].count().reset_index()

    student_id student_name subject_name  attended_exams
0            1        Alice         Math               3
1            1        Alice      Physics               2
2            1        Alice  Programming               1
3            2          Bob         Math               1
4            2          Bob      Physics               0
5            2          Bob  Programming               1
6            6         Alex         Math               0
7            6         Alex      Physics               0
8            6         Alex  Programming               0
9           13         John         Math               1
10          13         John      Physics               1
11          13         John  Programming               1

In [12]:
import pandas as pd
import numpy as np

students = pd.DataFrame({
    "student_id": [1, 2, 13, 6],
    "student_name": [np.nan, "Bob", "John", "Alex"]
})

subjects = pd.DataFrame({
    "subject_name": ["Math", "Physics", "Programming"]
})

examinations = pd.DataFrame({
    "student_id": [1, 1, 1, 2, 1, 1, 13, 13, 13, 2, 1],
    "subject_name": [
        "Math", "Physics", "Programming", "Programming",
        "Physics", "Math", "Math", "Programming",
        "Physics", "Math", "Math"
    ]
})

In [13]:
df_final.groupby(['student_id','student_name','subject_name'], dropna = False)['attended_exams'].count().reset_index()

    student_id student_name subject_name  attended_exams
0            1        Alice         Math               3
1            1        Alice      Physics               2
2            1        Alice  Programming               1
3            2          Bob         Math               1
4            2          Bob      Physics               0
5            2          Bob  Programming               1
6            6         Alex         Math               0
7            6         Alex      Physics               0
8            6         Alex  Programming               0
9           13         John         Math               1
10          13         John      Physics               1
11          13         John  Programming               1